### ISSUE TITLE
GitHubアカウント収集 2023

### ISSUE THREAD

**Issue by nguyenntt97** [nguyenntt97/ais_workshop#1]
アカウント登録が完了したら、このチケットの下にあるコメント欄から、授業中の実技演習に使用するアカウントをお知らせください。

## テンプレ

> 名前: グエン
> アカウントメール： nguyen.aislab@gmail.com

ご協力ありがとうございました。このワークショップが、皆様の今後の研究・業務にお役に立つことを願っております。

**Comment by Koki615** [comment]
> 名前: Koki615
> アカウントメール: honda.aislab@gmail.com

よろしくお願いします!

**Comment by nguyenntt97** [comment]
> > 名前: 本田 幸輝
> > アカウントメール: [honda.aislab@gmail.com](mailto:honda.aislab@gmail.com)
> 
>  #よろしくお願いします!

招待状をお送りしますので、ご確認ください。ご協力をありがとうございました。

**Comment by yuki55555** [comment]
よろしくお願いします。

**Comment by Yusuke080** [comment]
> 名前：鈴木優介
> アカウントメール：suzuki1.aislab@gmail.com

よろしくお願いします

**Comment by nguyenntt97** [comment]
> よろしくお願いします。

申し訳ございませんが、メールアドレスが抜けているようです。

**Comment by nguyenntt97** [comment]
> 招待状をお送りしますので、ご確認ください。ご協力をありがとうございました。

@Yusuke080  招待状をお送りしますので、ご確認ください。ご協力をありがとうございました。

**Comment by Kakeru923** [comment]
> 名前: 峯崎 翔琉
> アカウントメール： minesaki.aislab@gmail.com

よろしくお願いします。

**Comment by yuki55555** [comment]
設定しなおしてみました。

**Comment by yuki55555** [comment]
>遠藤優貴
>endo.aislab@gmail.com

すみません、ご確認お願いします。

**Comment by YuhiL** [comment]
名前: 錦織 勇飛
アカウントメール: ylink.90@outlook.jp
